Dasharo/coreboot

src/mainboard/protectli/vault_kbl/Kconfig
src/mainboard/protectli/vault_kbl/devicetree.cb

Signed-off-by: Igor Bagnucki <igor.bagnucki@3mdeb.com>

Fix device-tree location

---

.github/workflows/build.yml

Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>

.github/workflows/build.yml: add user info before checkout

---

build.sh

Signed-off-by: Igor Bagnucki <igor.bagnucki@3mdeb.com>

build.sh: Add support for I211 on FW6

---

.github/workflows/build.yml
.gitmodules

Clevo nv41mz CI

---

util/genbuild_h/genbuild_h.sh

Fix dasharo version number generation

---

dasharo/releases.yaml

dasharo/releases.yaml: Add new known issue

---

src/include/cpu/power/mvpd.h
src/include/symbols.h
src/mainboard/raptor-cs/talos-2/memlayout.ld
src/soc/ibm/power9/Makefile.inc
src/soc/ibm/power9/fsi.c
src/soc/ibm/power9/fsi.h
src/soc/ibm/power9/homer.c
src/soc/ibm/power9/i2c.c
src/soc/ibm/power9/mvpd.c
src/soc/ibm/power9/powerbus.c
src/soc/ibm/power9/pstates.c
src/soc/ibm/power9/tor.c

It's too early for a proper review of this, but sending in a PR in case there is something obviously wrong and there is nothing else to review.
Depends on PR #56

MVPD for second CPU

---

dasharo/project_config.yaml

Test: Run `data.py` and `run.py` and successfully generate newsletter and release page.

dasharo/project_config.yaml: fixes for updated dasharo-templates

---

dasharo/project_config.yaml

dasharo/project_config.yaml: Update release info

---

dasharo/releases.yaml

dasharo/releases.yaml: expand v1.0.0 changelog

---

src/ec/clevo/it5570/acpi/ec.asl
src/ec/clevo/it5570/acpi/lid.asl
src/ec/clevo/it5570/acpi/rgb_kb.asl

TODO: Call `KBUP ()` in a more appropriate place

Novacustom ns5x/rgb keyboard

---

src/mainboard/clevo/tgl-u/mainboard.c

mb/clevo/tgl-u/mainboard.c: disable AER for SSD RP

---

src/mainboard/protectli/vault_kbl/devicetree.cb

Signed-off-by: Igor Bagnucki <igor.bagnucki@3mdeb.com>

mb/protectli/kbl/devicetree: Lower the throttling temp to 75C

---

build.sh

build.sh: fix building cbfstool

---

src/cpu/x86/Kconfig
src/cpu/x86/mp_init.c
src/cpu/x86/smm/Makefile.inc
src/cpu/x86/smm/smm_module_handler.c
src/cpu/x86/smm/smm_module_loader.c
src/include/console/cbmem_console.h
src/include/cpu/x86/smm.h
src/lib/Makefile.inc
src/lib/cbmem_console.c

Cherry-pick https://review.coreboot.org/c/coreboot/+/63481/12 and its dependencies

Dasharo release/smm loader refactor

---

src/cpu/x86/Kconfig
src/cpu/x86/mp_init.c
src/cpu/x86/smm/Makefile.inc
src/cpu/x86/smm/smm_module_handler.c
src/cpu/x86/smm/smm_module_loader.c
src/include/console/cbmem_console.h
src/include/cpu/x86/smm.h
src/lib/Makefile.inc
src/lib/cbmem_console.c

Cherry-pick https://review.coreboot.org/c/coreboot/+/63481/12 and its dependencies

Protectli vault cml/smm loader refactor

---

dasharo/project_config.yaml

Signed-off-by: Przemyslaw Sulewski <przemyslaw.sulewski@3mdeb.com>

dasharo/project_config.yaml: improve links to documentation

---

dasharo/project_config.yaml

Signed-off-by: Przemyslaw Sulewski <przemyslaw.sulewski@3mdeb.com>

dasharo/project_config.yaml: improve links to HW and test matrixes

---

.github/workflows/build.yml
build.sh

Signed-off-by: Piotr Król <piotr.krol@3mdeb.com>

.github/workflows/build.yml: initial version

---

src/include/cpu/power/proc.h
src/include/cpu/power/scom.h
src/mainboard/raptor-cs/talos-2/Kconfig
src/soc/ibm/power9/fsi.c
src/soc/ibm/power9/istep_8_9.c

Also:
* fixes functions like `scom_and()` not producing SCOM logs
* exposed MAX_CPUS in menuconfig and started using it in code

Re-implement istep 8.9

---

src/soc/ibm/power9/istep_10_1.c
src/soc/ibm/power9/istep_8_11.c
src/soc/ibm/power9/powerbus.c

Fix isteps 8.11 and 10.1 for single cpu setup

---

dasharo/project_config.yaml
dasharo/releases.yaml

Signed-off-by: Michał Żygowski <michal.zygowski@3mdeb.com>

dasharo: add YAMLs

---

src/drivers/amd/amdmct/mct/mct_ddr3/mctdqs_d.c

Fixed logic for detecting passing read and write DQS delays
Force discard of negative DQS recovery delays

ASUS KGPE-D16: Fixed bugs in DQS Timing

---

src/soc/ibm/power9/homer.c
src/soc/ibm/power9/pstates.c

There are two reasons it can be disabled:
- chip doesn't support WOF
- no WOF table for the chip was found

soc/power9/pstates.c: handle disabled WOF properly

---

src/mainboard/protectli/vault_cml/hda_verb.c

vp4: fix hda verbs

---

.github/workflows/build.yml

Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>

.github/workflows/build.yml: bring back CI

---

payloads/external/skiboot/Kconfig
payloads/external/skiboot/Makefile
src/mainboard/raptor-cs/talos-2/1-cpu.dts
src/soc/ibm/power9/occ.c

This intends to fix https://github.com/Dasharo/dasharo-issues/issues/415 and https://github.com/Dasharo/dasharo-issues/issues/416.

Fix sensors and TPM

---

src/lib/timestamp.c

This change allows for proper parsing of timestamp table on platforms that use big endian in coreboot and little endian in target OS. POWER9 is an example of such architecture.
util/cbmem assumes that it runs on little endian system in most of its code, not only related to timestamps. This patch doesn't change that.
TEST=run cbmem -t on Talos 2, get sane results

lib/timestamp: explicitly write multibyte fields as little endian

---

capsule.sh

See https://github.com/Dasharo/docs/pull/881 for some usage information.

capsule.sh: script for capsule signing

---

capsule.sh

Small update to convert public key of root certificate in a form that can be consumed by EDK.

capsule.sh: generate EDK include with root's public key

---

src/drivers/efi/capsules.c

Nico pointed out some real and potential issues in https://review.coreboot.org/c/coreboot/+/83422.

Fix bug and handle overflows on capsule coalescing
