- Makefile.inc
- payloads/external/skiboot/Makefile
Replaces https://github.com/3mdeb/coreboot/pull/79
> Talos 2 Heads fixes

- src/include/cpu/power/spr.h
ISA lists those values in decimal, this change makes it easier to
compare with documentation. It also fixes wrong values for SRR0/SRR1.
Signed-off-by: Krystian Hebel <krystian.hebel@3mdeb.com>
Change-Id: I326f9ec73ab63c4c1cef836d3217e7132f49a4f5
> cpu/power/spr.h: change SPR numbers definitions to decimal

- src/mainboard/clevo/tgl-u/acpi/mainboard.asl
Remove bluetooth PowerResource from the mainboard ACPI code.
It was added as an attempt to get S0ix working, but is no longer needed.
Fixes bluetooth operation on Windows 10 with AX200 (PCIe) and AX201 (CNVi) cards.
S0ix is still entered according to `/sys/kernel/debug/pmc_core/package_cstate_show`.
Partially addresses issue https://gitlab.com/novacustom/dasharo-compatibility/-/issues/12
> mb/clevo/tgl-u/acpi/mainboard.asl: remove BT power resource

- src/mainboard/clevo/tgl-u/Kconfig
- src/mainboard/clevo/tgl-u/mainboard.c
Match the DMI fields of stock Insyde firmware.
Results in all hwids in fwupdtool being the same as in stock firmware - except the ones which include BIOS version and vendor:
```
user@user-NV4XMB-ME-MZ:~$ diff <(sudo fwupdtool hwids) <(cat hwids_stock.log)
3,6c3,6
< BiosVendor: 3mdeb Embedded Systems Consulting
< BiosVersion: Dasharo (coreboot+UEFI) v1.0.0
< BiosMajorRelease: 1
< BiosMinorRelease: 0
---
> BiosVendor: INSYDE Corp.
> BiosVersion: 1.07.06N
> BiosMajorRelease: 7
> BiosMinorRelease: 6
17,19c17,19
< {37b192b9-4fe8-5d20-b4e7-6d00782e2a09}   <- Manufacturer + Family + ProductName + ProductSku + BiosVendor + BiosVersion + BiosMajorRelease + BiosMinorRelease
< {bc90b4cf-a507-50c5-bf51-48c26863dc13}   <- Manufacturer + Family + ProductName + BiosVendor + BiosVersion + …
```
> Clevo nv41mz/smbios fixes

- src/drivers/gfx/nvidia/optimus/optimus.c
- src/mainboard/clevo/tgl-u/Kconfig
- src/mainboard/clevo/tgl-u/variants/nv41mz/devicetree.cb
Set correct subsystem ID for HD Audio device.
Needed for Windows drivers to load correct jack configuration.
Fixes [microphone input on Windows.](https://gitlab.com/novacustom/dasharo-compatibility/-/issues/15#note_822393261)
> mb/clevo/tgl-u/variants/nv41mz/devicetree.cb: set HDA subsystem ID

- src/include/symbols.h
- src/mainboard/raptor-cs/talos-2/memlayout.ld
- src/soc/ibm/power9/mvpd.c
MVPD is now read only once per CPU. I haven't checked how much time this saves exactly due to big fluctuations of serial output, but it is noticeably faster.
> soc/power9/mvpd.c: cache MVPD in memory between stages

- src/include/cpu/power/istep_8.h
- src/soc/ibm/power9/Makefile.inc
- src/soc/ibm/power9/istep_8_10.c
- src/soc/ibm/power9/istep_8_11.c
- src/soc/ibm/power9/istep_8_9.c
- src/soc/ibm/power9/romstage.c
- src/soc/ibm/power9/sbeio.c
- src/soc/ibm/power9/sbeio.h
Contains implementation of SBE SCOM and isteps 8.9-8.11. This only initializes XBus without fully configuring it for use, which seems to be responsibility of isteps 9.*
~~Comparing logs show that a couple of values in istep 8.10 differ from state CPU is in with Hostboot, but it's not clear if that's an issue and what might be causing the difference. Initialization of the second CPU should be identical up to that point.~~
Depends on #64 PR, and transitively on #57 and #56.
> XBus initialization

- src/include/cpu/power/istep_8.h
- src/include/cpu/power/istep_9.h
- src/soc/ibm/power9/Makefile.inc
- src/soc/ibm/power9/istep_8_10.c
- src/soc/ibm/power9/istep_8_11.c
- src/soc/ibm/power9/istep_8_9.c
- src/soc/ibm/power9/istep_9_2.c
- src/soc/ibm/power9/istep_9_4.c
- src/soc/ibm/power9/istep_9_6.c
- src/soc/ibm/power9/istep_9_7.c
- src/soc/ibm/power9/romstage.c
- src/soc/ibm/power9/xbus.c
- src/soc/ibm/power9/xbus.h
This contains implementation of relevant parts of isteps 9.2, 9.4, 9.6 and 9.7 (XBus only, no OBus). The rest of 9.* isteps group are either empty (debug stuff only, 9.3 and 9.5), not required at least at this point (lane repair information in 9.1) or don't apply (link aggregation in 9.8 doesn't seem to be our case).
Based on PR #65
> XBus / SMP link configuration

- src/drivers/pc80/tpm/tis.c
- src/mainboard/clevo/tgl-u/variants/baseboard/devicetree.cb
- src/mainboard/clevo/tgl-u/variants/ns50mu/overridetree.cb
- src/mainboard/clevo/tgl-u/variants/nv41mz/overridetree.cb
- move hda device to overridetrees to fix SSID setting
- remove TPM IRQ setting from devicetree
- use hardcoded TPM path recognized by Windows
> mb/clevo/tgl-u: windows fixes

- src/soc/intel/tigerlake/acpi/tcss.asl
- src/soc/intel/tigerlake/pmc.c
Hide devices that appear as `Unknown Devices` in Windows Device Manager.
> soc/intel/tigerlake: hide IOM and PMC devices in ACPI

- dasharo/project_config.yaml
`dasharo.platform` has to be the same as the name of the platform in the release tag.
> tuxedo_ibs15 project config: fix platform name and test spec link

- build.sh
Fixes building vboot testing binaries in CI.
> build.sh: install vboot utils locally

- src/include/cpu/power/occ.h
- src/lib/device_tree.c
- src/mainboard/raptor-cs/talos-2/Kconfig
- src/mainboard/raptor-cs/talos-2/memlayout.ld
- src/soc/ibm/power9/homer.c
- src/soc/ibm/power9/occ.c
Apart from CPU-specific SCOM accesses, this re-organizes 21.1 to start multiple OCCs.
> Start OCC for the second CPU

- src/include/cpu/power/istep_10.h
- src/soc/ibm/power9/Makefile.inc
- src/soc/ibm/power9/istep_10_6.c
- src/soc/ibm/power9/romstage.c
Without this istep, skiboot checkstops for two CPUs during XIVE initialization.
> Implement istep 10.6

- src/include/cpu/power/istep_10.h
- src/soc/ibm/power9/chip.c
- src/soc/ibm/power9/istep_10_13.c
- src/soc/ibm/power9/romstage.c
Without this Debian hangs on network initialization.
> Initialize RNG for second CPU

- src/include/cpu/power/istep_10.h
- src/include/cpu/power/istep_18.h
- src/soc/ibm/power9/chip.c
- src/soc/ibm/power9/istep_10_13.c
- src/soc/ibm/power9/istep_18_11.c
- src/soc/ibm/power9/istep_18_12.c
- src/soc/ibm/power9/romstage.c
Update isteps 18.11 and 18.12 to also work with 2 CPUs.
> Configure TOD for up to two CPUs

- src/soc/ibm/power9/istep_14_1.c
- src/soc/ibm/power9/istep_8_4.c
- src/soc/ibm/power9/istep_9_2.c
- src/soc/ibm/power9/istep_9_7.c
- src/soc/ibm/power9/mcbist.c
- src/soc/ibm/power9/romstage.c
As a side effect of trying to do things concurrently, code was measured and it became evident that it can run faster after small reorganization: polling at higher frequency, starting things in parallel or after removing superfluous delays.
* baseline: 34.84 seconds
* with these changes: 31.24 seconds
* with these changes and OCC changes (part of #94): 27.22 seconds
The slowest part currently  is building MVPD (13 seconds, 9 for building MVPD of the second CPU), reading cached version from PNOR should take just 50 milliseconds.
> Faster load

- build.sh
> build.sh: enable UEFI Secure Boot

- src/ec/clevo/it5570/acpi/cmos.asl
- src/ec/clevo/it5570/acpi/ec.asl
- src/ec/clevo/it5570/acpi/rgb_kb.asl
- src/mainboard/clevo/tgl-u/cmos.default
- src/mainboard/clevo/tgl-u/cmos.layout
Add persistent keyboard implementation for laptops with RGB keyboards like NS5x.
Store the keyboard settings in CMOS. Add defaults: Enabled, White color, 20% brightness.
> ec/clevo/it5570: store keyboard backlight in CMOS

- build.sh
Signed-off-by: Michał Żygowski <michal.zygowski@3mdeb.com>
> build.sh: bump patchset to a version with serial number and UUID in CBFS

- .gitmodules
Storing it between boots doesn't work well for OSes that can't clear the stored state.
> Use Dasharo fork of vboot with non-volatile recovery reason

- src/soc/ibm/power9/homer.c
- src/soc/ibm/power9/romstage.c
Fixes some issues in Dasharo/dasharo-issues#80 (GitHub won't close the issue on merging this PR).
Tested by making `fsi_get_present_chips()` return `0x01`. Potentially, there can be other issues, but Linux boots fine with hard-coded mask after these fixes.
> Fixes for single CPU setup

- payloads/external/Makefile.inc
- payloads/external/skiboot/Kconfig
- payloads/external/skiboot/Makefile
- src/commonlib/include/commonlib/cbmem_id.h
- src/lib/coreboot_table.c
- src/security/tpm/tspi.h
- src/security/tpm/tspi/log-tpm.c
- src/soc/ibm/power9/chip.c
- util/cbmem/cbmem.c
This includes cleaned up changes from https://github.com/Dasharo/coreboot/pull/62, because they were necessary.
If https://github.com/Dasharo/skiboot/pull/2 is merged first, this PR can be changed to update skiboot payload to use that fork.
> Make cbmem work and print TCPA log

- src/soc/intel/common/block/cse/cse.c
A draft as there might be issues with ME disabled. If not, I guess this PR can be used to make it optional depending on an EFI variable.
Can be reviewed though, in case something was done wrong. Enabling ME wasn't tested yet.
> Disable ME on Protectli VP4620

- src/soc/ibm/power9/istep_10_1.c
- src/soc/ibm/power9/xscom.c
It's write-only and doesn't even return any status unlike form 0.
> soc/power9/xscom.c: handle form 1 of indirect SCOM

- src/soc/ibm/power9/istep_13_8.c
After deeper analysis hardcoded values are always used, despite the
amount of Hostboot code that calculates different values.
Signed-off-by: Krystian Hebel <krystian.hebel@3mdeb.com>
Change-Id: I9d70b7a2936751066d3b675580cf5d89fc7a480c
> soc/power9/istep_13_8.c: remove wrong debug line

- src/superio/ite/common/early_serial.c
Set the watchdog timer timeout to 0. The default value of 56 minutes caused unwanted reboots.
> mb/protectli/vault_cml/bootblock.c: set WDT timeout to 0

- src/southbridge/amd/sb700/Makefile.inc
- src/southbridge/amd/sb700/bootblock.c
- src/southbridge/amd/sb700/pci.c
- src/southbridge/amd/sb700/sm.c
- src/southbridge/amd/sb700/smbus.c
Signed-off-by: Michał Żygowski <michal.zygowski@3mdeb.com>
> southbridge/amd/sb700: Add missing PCI bridge initialization and fix SB MMIO init

- src/mainboard/clevo/adl-p/cmos.layout
Fixes https://github.com/Dasharo/dasharo-issues/issues/242
> mb/clevo/adl-p/cmos.layout: exclude vbnv from checksums

- src/mainboard/clevo/adl-p/variants/ns50pu/overridetree.cb
- src/mainboard/clevo/adl-p/variants/nv40pz/overridetree.cb
Fixes Win11 BSODs while an Ethernet cable is connected.
Addresses https://github.com/Dasharo/dasharo-issues/issues/264
> mb/clevo/adl-p/variants: disable AER for GbE RP

- src/commonlib/bsd/include/commonlib/bsd/helpers.h
This protects against some of unintentional integer promotions, e.g.:
uint16_t freq_mhz = 2148;  // or bigger
uint64_t freq = freq_mhz * MHz;
In this example, MHz used to be treated as int32_t, and because int32_t can represent every value that uin16_t can, multiplication was being performed with both arguments treated as int32_t. During assignment, result of multiplication is promoted to int64_t (because it can represent each value that int32_t can), and finally implicitly converted to uint64_t.
Promotions preserve the value, including the sign, so if result of multiplication is negative, the same negative number (but extended to 64 bits) is converted to unsigned number.
Signed-off-by: Krystian Hebel <krystian.hebel@3mdeb.com>
Change-Id: Id90af1b769b502d712c11b87c2bdcc7472737050
> commonlib/helpers.h: use unsigned literals in definitions

- src/ec/system76/ec/acpi/cmos.asl
- src/ec/system76/ec/acpi/ec.asl
- src/ec/system76/ec/acpi/s76.asl
- src/mainboard/clevo/adl-p/cmos.default
- src/mainboard/clevo/adl-p/cmos.layout
- src/mainboard/clevo/tgl-u/cmos.default
- src/mainboard/clevo/tgl-u/cmos.layout
- src/soc/intel/common/block/cse/cse.c
Tested on NS50PU. Works, but setting is overriden later in the boot process by the `system76_acpi` driver. Should probably stop relying on it and either use standard ACPI interfaces or have our own OS driver.
Depends on https://github.com/Dasharo/ec/pull/17
> Persistent keyboard backlight

- src/mainboard/msi/ms7d25/devicetree.cb
- src/soc/intel/alderlake/chip.h
- src/soc/intel/alderlake/fsp_params.c
Tested on all 6 full-size SATA ports. Enabled HP for the M.2 slots with SATA capability as well, note that you wouldn't want to hotplug M.2 disks directly, but it may be useful if using some sort of adapter to a fullsize SATA port or another electrically hot-plugable connector.
Fixes https://github.com/Dasharo/dasharo-issues/issues/315
> Msi ms7d25/sata hp

- src/mainboard/clevo/tgl-u/acpi/touchpad.asl
- src/mainboard/clevo/tgl-u/variants/ns50mu/devicetree.cb
Was mistakenly dropped during a rebase.
Should fix https://github.com/Dasharo/dasharo-issues/issues/313
> ns5x_tgl: restore ELAN touchpad support

- src/ec/system76/ec/acpi/s76.asl
When rebooting, the lid switch state does not change, so the EC will not automatically reenable backlight. Call EKBL during boot to fix this.
> ec/system76/ec/acpi/s76.asl: reenable keyboard on reboot

- src/mainboard/clevo/adl-p/variants/ns50pu/overridetree.cb
- src/mainboard/clevo/adl-p/variants/nv40pz/overridetree.cb
- src/mainboard/clevo/tgl-u/variants/ns50mu/devicetree.cb
- src/mainboard/clevo/tgl-u/variants/nv40mz/devicetree.cb
Set default limits as if the barrel jack AC adapter is used. These limits are adjusted later by EC.
> Novacustom power limits

- util/crossgcc/buildgcc
Otherwise downstream projects (Nitrokey, Then Heads) cannot build release correctly and forks Dasharo.
This should deserve a point release (1.6.1) ASAP and commit usable under https://github.com/osresearch/heads/pull/1417 otherwise we are taking really weird direction.
----
See https://github.com/Nitrokey/coreboot/tree/nitropad-v2.2 as proposed under https://github.com/osresearch/heads/pull/1417/files#diff-18936189b28399cf48703d0c1ec1df33e57c559de2a12f4438be00e6813bdb68R49-R53 which should point to Dasharo, not be cloned to fix upstream.
> Fix unbuildable clevo-release: change acpica-unix2 location to a mirror

- src/soc/intel/alderlake/acpi.c
Desktop processors do not report C7 substate support in CPUID. Use C8 which
is the first supported lower state than C7 state, which is C8. This fixes
the unsupported C-state Firmware Bug in Linux dmesg.
> src/soc/intel/alderlake/acpi.c: Fix reported C-states on desktop processors

- src/ec/system76/ec/acpi/ec.asl
- src/ec/system76/ec/acpi/ec_ram.asl
- src/ec/system76/ec/acpi/s76.asl
- src/ec/system76/ec/system76_ec.c
- src/mainboard/clevo/tgl-u/acpi/sleep.asl
S0ix PMC hack relies on reading ECOS field, so it has to be read no matter which sleep type we are entering
> S0ix fixes after EC rebase

- payloads/external/iPXE/Makefile
Allow using the $CPUS variable to control how many jobs are used for building iPXE. Consideralby speeds up compilation when building coreboot with `CPUS=17 NUM_CPUS=17 make -j17` on an i5-1240P (until now, iPXE took the longest to build of all Dasharo components)
> payloads/external/iPXE/Makefile: build using $CPUS jobs

- src/mainboard/clevo/tgl-u/acpi/backlight.asl
- src/mainboard/clevo/tgl-u/acpi/mainboard.asl
- src/mainboard/clevo/tgl-u/dsdt.asl
Add the same linear backlight levels that we use for ADL-P models, in place of coreboot's default exponential levels.
> mb/clevo/tgl-u: add backlight levels in line with adl-p

- src/mainboard/msi/ms7d25/smihandler.c
- src/mainboard/msi/ms7e06/smihandler.c
- src/superio/nuvoton/nct6687d/superio.c
Configures blinking LED on S3 sleep, PS/2 KBD and mouse wake from S3/S4. Also added a bit that is enabled by MSI firmware to handle power loss. Maybe this was causing issues reported during validation of the power status after power fail feature (at least it worked for me without any modifications).
> Msi ms7d25/sio power config

- src/ec/system76/ec/acpi/ec.asl
- src/ec/system76/ec/acpi/ec_ram.asl
- src/soc/intel/alderlake/hsphy.c
- src/soc/intel/alderlake/romstage/fsp_params.c
- src/soc/intel/common/block/vtd/vtd.c
- src/soc/intel/tigerlake/romstage/fsp_params.c
Hide the TBT DMA devices so Windows stops complaining about missing drivers. Verify that XDomain networking still works under Linux. ATM it's not possible to verify if other USB4 tunneling functionality is working.
Needs https://github.com/Dasharo/ec/pull/52
> Nvc tbt fixes

- src/mainboard/protectli/vault_jsl/devicetree.cb
TPMs in coreboot have to be in PCI domain scope, because the TPM memory is advertised in the ACPI under SB.PCI0 as resource producer. If TPM is not under SB.PCI0 in ACPI, then WIndows will eb unable to claim the TPM memory for TPM ACPI device.
> mainboard/protectli/vault_jsl: Fix CRB TPM scope in devicetree

- src/mainboard/protectli/vault_ehl/mainboard.c
HWP is too aggressive in power savings and does not let using full bandwidth of Ethernet controllers without additional stressing of the CPUs (2Gb/s vs 2.35Gb/s with stressing, measured with iperf3). Let the Linux use acpi-cpufreq governor driver instead of intel_pstate by disabling HWP.
> mainboard/protectli/vault_ehl: Disable HWP

- Documentation/drivers/smmstorev2.md
- src/drivers/efi/capsules.c
- src/drivers/smmstore/smi.c
- src/drivers/smmstore/store.c
- src/include/smmstore.h
Depends on https://github.com/Dasharo/edk2/pull/133
> Fw update smi2

- src/security/vboot/Makefile.mk
futility always prints a warning when building:
WARNING: prepare_slot: VBLOCK_A keyblock is invalid.
This is the expected state, because at that point vblock hasn't been created yet.
Pipe warnings to /dev/null to prevent worrying users unnecesarily.
Change-Id: I93fd5dafe220bafcf5325ecd4f9f4ee94fc3f81f
> security/vboot/Makefile.mk: silence warnings when signing binary

- src/mainboard/protectli/vault_jsl/devicetree.cb
The board does not support SATA disks. Despite the M.2 slots have the SATA lines, the silicon does not support the dynamic switching between SATA and PCIe. Disable the SATA controller to make Windows happy, as the straps are set for PCIe lanes.
> mainboard/protectli/vault_jsl/devicetree.cb: Disable SATA

- src/include/smbios.h
- src/lib/smbios.c
- src/lib/smbios_defaults.c
- src/mainboard/protectli/vault_jsl/Kconfig
- src/mainboard/protectli/vault_jsl/devicetree.cb
- src/mainboard/protectli/vault_jsl/hda_verb.c
- src/mainboard/protectli/vault_jsl/mainboard.c
- src/mainboard/protectli/vault_jsl/overridetree_v1610.cb
Eliminating differences in SMBIOS compared to proprietary firmware to make Windows Update happy.
UPDATE: SMBIOS did not help at all with fetching drivers. But skipping PCI SSID programming made the audio driver probe at least.
> Vault JSL Windows audio driver probe fix

- src/soc/intel/common/block/acpi/cpu_hybrid.c
MADT LAPIC entries were generated for all CPUs in range 0 to CONFIG_MAX_CPUS regardless of their existence. This caused the cpu->path.apic.core_type field to have a different value than specified in cpu_perf_eff_type enum and extra efficient cores being added to the list with an unusuallly high APIC ID dereferenced from NULL pointer. For systems which obtain LAPICs/CPUs topology from MADT, like ESXI, it resulted in finding more CPUs than available in the system (exactly one more core in case of ESXi, because other entries had the same ACPI ID and were ignored as duplicates). SMP initialization failed in such case with timeout on waking a non-existent CPU core.
TEST=Boot ESXi in headless mode on VP6670.
> VP6670 ESXi fix

- .github/workflows/build.yml
This should fix deploy failures like https://github.com/Dasharo/coreboot/actions/runs/10309184293/job/28539370198
> .github/workflows/build.yml: remove obesolete variable matrix.build

- src/soc/intel/meteorlake/romstage/romstage.c
Applied Miczyg1's patch to coreboot alder lake https://review.coreboot.org/c/coreboot/+/68450 to meteor lake. It should hopefully fix this issue https://github.com/Dasharo/dasharo-issues/issues/985 but I can't test it now because of missing FSP.
> soc/intel/meteorlake: Hook the VT-d DMA protection option

- .gitignore
Just a small change to cover more build artifacts
> .gitignore: Ignore both roms and their sha256

- src/mainboard/clevo/mtl-h/ramstage.c
These UPDs have to be set for PCH USB2.0 ports that are paired with CPU XHCI controller.
> mb/clevo/mtl-h/ramstage.c: Add port reset message for USB ports 2 and 6
